template: |
  ## Changes
  $CHANGES

name-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 🚀 Features
    labels: ['feature', 'enhancement']
  - title: 🛠 Fixes
    labels: ['bug', 'fix']
  - title: 📚 Docs
    labels: ['docs']
  - title: 🧰 Internal
    labels: ['chore', 'ci', 'build']

change-template: '- $TITLE (#$NUMBER) @${AUTHOR}'

no-changes-template: 'No user-facing changes.'
