name: Release Notes

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
